[package]
name = "queens-8-puzzle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
bracket-lib = "0.8.1"
plotters = "0.3.2"